[package]
name = "ecdsa-verify-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
k256 = { version = "0.13.3", default-features = false, features = [
    "alloc",
    "ecdsa",
] }
