[package]
name = "ecdsa-recover-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
sha2 = { version = "0.10", default-features = false }
secp256k1 = { version = "0.28.2", default-features = false, features = [
    "alloc",
    "recovery",
    "lowmemory"
] }
